#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# sudo yabai --load-sa
#

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_topmost               off        \
    window_zoom_persist          on             \
    window_shadow                float             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity               off            \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.40           \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  3             \
    bottom_padding               3             \
    left_padding                 3             \
    right_padding                3             \
    window_gap                   3             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

yabai -m rule --add app="^System Settings$" sub-layer=above manage=off
yabai -m rule --add app="^Calculator$" sub-layer=above manage=off
yabai -m rule --add app="^Finder$" sub-layer=above manage=off
yabai -m rule --add app="^Karabiner-Elements$" sub-layer=above manage=off
yabai -m rule --add app="^MenuMeters$" sub-layer=above manage=off
yabai -m rule --add app="^Step Two$" sub-layer=above manage=off
yabai -m rule --add app="^Messages$" sub-layer=above manage=off
yabai -m rule --add app="^Calendar$" sub-layer=above manage=off
yabai -m rule --add app="^Signal$" sub-layer=above manage=off

yabai -m config external_bar all:25:0
borders active_color=0xffebd234 inactive_color=0xff555555 width=6.0

echo "yabai configuration loaded.."
